using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class LearningScenarioStart : MonoBehaviour
{
    public enum ScenarioState
    {
        Idle,
        IntroAnimating,
        LibraryVisible,
        Inspecting,
        ReturningFromInspect
    }

    [System.Serializable]
    public class LibraryComponentEntry
    {
        public string id = "Component";
        public Transform componentRoot;
        public Transform libraryWindowRoot;
        public Transform libraryAnchor;
    }

    [Header("UI Controls")]
    public Button startButton;
    public Button backButton;

    [Header("Main Sequence")]
    public OpenComponentVR pcCaseDoor;
    public Transform pcCaseDoorObject;
    public Transform playerHead;
    public Transform inspectAnchor;

    [Header("Case Door Fly Away")]
    public bool animateCaseDoorFlyAway = true;
    public float caseDoorFlyDuration = 0.9f;
    public float caseDoorFlyDistance = 2f;
    public float caseDoorFlyUpOffset = 0.7f;
    public float caseDoorFlyRotateDegrees = 70f;
    public bool hideCaseDoorAfterFly = true;

    [Header("Intro: six components first")]
    public List<LibraryComponentEntry> introComponents = new List<LibraryComponentEntry>();
    public List<Transform> introRevealAnchors = new List<Transform>();

    [Header("Library: remaining components")]
    public List<LibraryComponentEntry> additionalComponents = new List<LibraryComponentEntry>();

    [Header("Auto Generation")]
    public bool autoGenerateWindows = true;
    public GameObject windowPrefab;
    public Transform windowParent;
    public Vector2 placeholderWindowSize = new Vector2(0.28f, 0.2f);
    public float placeholderWindowDepth = 0.02f;
    public Color placeholderWindowColor = new Color(0.16f, 0.18f, 0.22f, 1f);
    public Color placeholderBorderColor = new Color(0.7f, 0.77f, 0.9f, 1f);
    public Color placeholderHeaderColor = new Color(0.2f, 0.55f, 0.95f, 1f);
    public bool autoGenerateArcLayout = true;
    public float libraryRadius = 1.6f;
    public float libraryArcDegrees = 120f;
    public float libraryHeightOffset = -0.1f;
    public Transform libraryCenterOverride;
    public float libraryForwardOffset = 1.35f;
    public float minimumLibraryY = 0.75f;
    public bool autoGenerateRevealAnchors = true;
    public float revealDistanceFromCase = 0.35f;
    public float revealHeightFromCase = 0.22f;
    public float revealArcDegrees = 55f;

    [Header("Timing")]
    public float caseOpenLeadTime = 0.7f;
    public float moveDuration = 0.8f;
    public float introStagger = 0.12f;
    public float libraryStagger = 0.08f;
    public bool animateIntroInParallel = true;
    public bool animateAdditionalInParallel = true;
    public float inspectEnterDuration = 0.45f;
    public float inspectExitDuration = 0.45f;

    [Header("Animation")]
    public float hiddenScaleMultiplier = 0.05f;
    public float moveAwayDistance = 2.5f;
    public float moveAwayUpOffset = 0.5f;
    public bool moveHiddenItemsForward = true;
    public float hiddenItemsForwardDistance = 2.2f;
    public float hiddenItemsForwardSpread = 0.65f;
    public float inspectScaleMultiplier = 1.25f;
    public AnimationCurve movementCurve = AnimationCurve.EaseInOut(0f, 0f, 1f, 1f);

    [Header("Player Movement")]
    public bool disablePlayerMovementInScene = true;
    public List<Behaviour> movementBehavioursToDisable = new List<Behaviour>();

    public ScenarioState CurrentState => currentState;

    private readonly List<LibraryComponentEntry> allComponents = new List<LibraryComponentEntry>();
    private readonly Dictionary<Transform, CachedTransformData> originalComponentData = new Dictionary<Transform, CachedTransformData>();
    private readonly Dictionary<Transform, Vector3> originalWindowScale = new Dictionary<Transform, Vector3>();

    private LibraryComponentEntry selectedEntry;
    private ScenarioState currentState = ScenarioState.Idle;
    private Coroutine sequenceRoutine;

    private struct CachedTransformData
    {
        public Vector3 position;
        public Quaternion rotation;
        public Vector3 localScale;
    }

    private struct DoorPoseData
    {
        public Vector3 position;
        public Quaternion rotation;
        public bool active;
    }

    private bool hasDoorPose;
    private DoorPoseData doorPose;
    private readonly List<Behaviour> runtimeDisabledMovementBehaviours = new List<Behaviour>();

    private void Awake()
    {
        CollectUniqueEntries();
        EnsureAutoGeneratedSceneData();
        CacheOriginalData();
    }

    private void OnEnable()
    {
        if (startButton != null)
            startButton.onClick.AddListener(StartScenario);

        if (backButton != null)
            backButton.onClick.AddListener(ExitInspectMode);
    }

    private void OnDisable()
    {
        if (startButton != null)
            startButton.onClick.RemoveListener(StartScenario);

        if (backButton != null)
            backButton.onClick.RemoveListener(ExitInspectMode);

        SetMovementLocked(false);
    }

    private void Start()
    {
        PrepareInitialState();
        SetMovementLocked(disablePlayerMovementInScene);
    }

    public void StartScenario()
    {
        if (currentState != ScenarioState.Idle)
            return;

        if (sequenceRoutine != null)
            StopCoroutine(sequenceRoutine);

        sequenceRoutine = StartCoroutine(RunMainSequence());
    }

    public void SelectComponentById(string componentId)
    {
        if (string.IsNullOrWhiteSpace(componentId) || currentState != ScenarioState.LibraryVisible)
            return;

        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry != null && entry.id == componentId)
            {
                BeginInspect(entry);
                return;
            }
        }
    }

    public void SelectComponent(Transform componentRoot)
    {
        if (componentRoot == null || currentState != ScenarioState.LibraryVisible)
            return;

        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry != null && entry.componentRoot == componentRoot)
            {
                BeginInspect(entry);
                return;
            }
        }
    }

    public void SelectFromWindow(Transform windowRoot)
    {
        if (windowRoot == null || currentState != ScenarioState.LibraryVisible)
            return;

        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry != null && entry.libraryWindowRoot == windowRoot)
            {
                BeginInspect(entry);
                return;
            }
        }
    }

    public void ExitInspectMode()
    {
        if (currentState != ScenarioState.Inspecting || selectedEntry == null)
            return;

        if (sequenceRoutine != null)
            StopCoroutine(sequenceRoutine);

        sequenceRoutine = StartCoroutine(ReturnFromInspect());
    }

    private void BeginInspect(LibraryComponentEntry entry)
    {
        if (entry == null || entry.componentRoot == null)
            return;

        if (sequenceRoutine != null)
            StopCoroutine(sequenceRoutine);

        sequenceRoutine = StartCoroutine(EnterInspect(entry));
    }

    private IEnumerator RunMainSequence()
    {
        currentState = ScenarioState.IntroAnimating;
        SetStartButtonEnabled(false);
        SetBackButtonVisible(false);
        SetLibraryInteractable(false);

        if (!animateCaseDoorFlyAway && pcCaseDoor != null)
            pcCaseDoor.ToggleOpen();

        if (animateCaseDoorFlyAway && pcCaseDoorObject != null)
            yield return StartCoroutine(AnimateCaseDoorFlyAway());

        if (caseOpenLeadTime > 0f)
            yield return new WaitForSeconds(caseOpenLeadTime);

        if (animateIntroInParallel)
        {
            float introBatchDuration = StartIntroBatchParallel();
            if (introBatchDuration > 0f)
                yield return new WaitForSeconds(introBatchDuration);
        }
        else
        {
            for (int i = 0; i < introComponents.Count; i++)
            {
                var entry = introComponents[i];
                if (entry == null || entry.componentRoot == null)
                    continue;

                Transform revealAnchor = i < introRevealAnchors.Count ? introRevealAnchors[i] : null;
                yield return StartCoroutine(AnimateIntroEntry(entry, revealAnchor));

                if (introStagger > 0f)
                    yield return new WaitForSeconds(introStagger);
            }
        }

        if (animateAdditionalInParallel)
        {
            float additionalBatchDuration = StartAdditionalBatchParallel();
            if (additionalBatchDuration > 0f)
                yield return new WaitForSeconds(additionalBatchDuration);
        }
        else
        {
            for (int i = 0; i < additionalComponents.Count; i++)
            {
                var entry = additionalComponents[i];
                if (entry == null || entry.componentRoot == null)
                    continue;

                yield return StartCoroutine(AnimateAdditionalEntryIn(entry));

                if (libraryStagger > 0f)
                    yield return new WaitForSeconds(libraryStagger);
            }
        }

        currentState = ScenarioState.LibraryVisible;
        SetLibraryInteractable(true);
    }

    private IEnumerator AnimateIntroEntry(LibraryComponentEntry entry, Transform revealAnchor)
    {
        entry.componentRoot.gameObject.SetActive(true);
        SetComponentPhysicsAnimated(entry.componentRoot, true);

        if (entry.libraryWindowRoot != null)
        {
            entry.libraryWindowRoot.gameObject.SetActive(true);

            if (originalWindowScale.TryGetValue(entry.libraryWindowRoot, out Vector3 winScale))
                entry.libraryWindowRoot.localScale = Vector3.zero;
            else
                winScale = Vector3.one;

            StartCoroutine(AnimateScale(entry.libraryWindowRoot, winScale, moveDuration * 0.8f));
        }

        if (revealAnchor != null)
        {
            yield return StartCoroutine(AnimateTransform(entry.componentRoot, revealAnchor.position, revealAnchor.rotation, entry.componentRoot.localScale, moveDuration));
        }

        Transform anchor = GetAnchor(entry);
        if (anchor != null)
        {
            yield return StartCoroutine(AnimateTransform(entry.componentRoot, anchor.position, anchor.rotation, entry.componentRoot.localScale, moveDuration));
        }
    }

    private float StartIntroBatchParallel()
    {
        float maxTime = 0f;

        for (int i = 0; i < introComponents.Count; i++)
        {
            var entry = introComponents[i];
            if (entry == null || entry.componentRoot == null)
                continue;

            Transform revealAnchor = i < introRevealAnchors.Count ? introRevealAnchors[i] : null;
            float delay = Mathf.Max(0f, introStagger) * i;
            StartCoroutine(AnimateIntroEntryDelayed(entry, revealAnchor, delay));

            float entryDuration = revealAnchor != null ? moveDuration * 2f : moveDuration;
            maxTime = Mathf.Max(maxTime, delay + entryDuration);
        }

        return maxTime;
    }

    private float StartAdditionalBatchParallel()
    {
        float maxTime = 0f;

        for (int i = 0; i < additionalComponents.Count; i++)
        {
            var entry = additionalComponents[i];
            if (entry == null || entry.componentRoot == null)
                continue;

            float delay = Mathf.Max(0f, libraryStagger) * i;
            StartCoroutine(AnimateAdditionalEntryInDelayed(entry, delay));
            maxTime = Mathf.Max(maxTime, delay + moveDuration);
        }

        return maxTime;
    }

    private IEnumerator AnimateIntroEntryDelayed(LibraryComponentEntry entry, Transform revealAnchor, float delay)
    {
        if (delay > 0f)
            yield return new WaitForSeconds(delay);

        yield return StartCoroutine(AnimateIntroEntry(entry, revealAnchor));
    }

    private IEnumerator AnimateAdditionalEntryInDelayed(LibraryComponentEntry entry, float delay)
    {
        if (delay > 0f)
            yield return new WaitForSeconds(delay);

        yield return StartCoroutine(AnimateAdditionalEntryIn(entry));
    }

    private IEnumerator AnimateAdditionalEntryIn(LibraryComponentEntry entry)
    {
        Transform anchor = GetAnchor(entry);
        if (anchor == null)
            yield break;

        entry.componentRoot.gameObject.SetActive(true);
        SetComponentPhysicsAnimated(entry.componentRoot, true);

        Vector3 originalScale = entry.componentRoot.localScale;
        Vector3 startOffset = anchor.position + (Vector3.up * 0.45f);
        entry.componentRoot.position = startOffset;
        entry.componentRoot.rotation = anchor.rotation;
        entry.componentRoot.localScale = Vector3.one * hiddenScaleMultiplier;

        if (entry.libraryWindowRoot != null)
        {
            entry.libraryWindowRoot.gameObject.SetActive(true);
            entry.libraryWindowRoot.localScale = Vector3.zero;

            if (originalWindowScale.TryGetValue(entry.libraryWindowRoot, out Vector3 winScale))
                StartCoroutine(AnimateScale(entry.libraryWindowRoot, winScale, moveDuration * 0.7f));
        }

        yield return StartCoroutine(AnimateTransform(entry.componentRoot, anchor.position, anchor.rotation, originalScale, moveDuration));
    }

    private IEnumerator EnterInspect(LibraryComponentEntry entry)
    {
        currentState = ScenarioState.IntroAnimating;
        selectedEntry = entry;

        SetLibraryInteractable(false);
        SetBackButtonVisible(false);

        Vector3 referencePos = GetReferencePosition();

        for (int i = 0; i < allComponents.Count; i++)
        {
            var current = allComponents[i];
            if (current == null || current == selectedEntry)
                continue;

            AnimateEntryAway(current, referencePos, inspectEnterDuration);
        }

        if (selectedEntry.libraryWindowRoot != null)
            StartCoroutine(AnimateAndHide(selectedEntry.libraryWindowRoot, inspectEnterDuration * 0.8f));

        yield return new WaitForSeconds(inspectEnterDuration);

        if (inspectAnchor != null && selectedEntry.componentRoot != null)
        {
            Vector3 targetScale = selectedEntry.componentRoot.localScale * inspectScaleMultiplier;
            yield return StartCoroutine(AnimateTransform(
                selectedEntry.componentRoot,
                inspectAnchor.position,
                inspectAnchor.rotation,
                targetScale,
                inspectEnterDuration));
        }

        SetInspectRotationEnabled(selectedEntry.componentRoot, true);
        SetBackButtonVisible(true);
        currentState = ScenarioState.Inspecting;
    }

    private IEnumerator ReturnFromInspect()
    {
        currentState = ScenarioState.ReturningFromInspect;
        SetBackButtonVisible(false);

        if (selectedEntry != null && selectedEntry.componentRoot != null)
        {
            SetInspectRotationEnabled(selectedEntry.componentRoot, false);

            Transform selectedAnchor = GetAnchor(selectedEntry);
            if (selectedAnchor != null)
            {
                Vector3 returnScale = GetOriginalScale(selectedEntry.componentRoot);
                yield return StartCoroutine(AnimateTransform(
                    selectedEntry.componentRoot,
                    selectedAnchor.position,
                    selectedAnchor.rotation,
                    returnScale,
                    inspectExitDuration));
            }

            if (selectedEntry.libraryWindowRoot != null)
            {
                selectedEntry.libraryWindowRoot.gameObject.SetActive(true);
                selectedEntry.libraryWindowRoot.localScale = Vector3.zero;
                if (originalWindowScale.TryGetValue(selectedEntry.libraryWindowRoot, out Vector3 winScale))
                    StartCoroutine(AnimateScale(selectedEntry.libraryWindowRoot, winScale, inspectExitDuration * 0.8f));
            }
        }

        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry == null || entry == selectedEntry)
                continue;

            RestoreEntryFromHidden(entry, inspectExitDuration);
        }

        yield return new WaitForSeconds(inspectExitDuration);

        SetLibraryInteractable(true);
        currentState = ScenarioState.LibraryVisible;
    }

    private void AnimateEntryAway(LibraryComponentEntry entry, Vector3 referencePos, float duration)
    {
        if (entry.componentRoot != null && entry.componentRoot.gameObject.activeInHierarchy)
        {
            Vector3 targetPos;
            if (moveHiddenItemsForward)
            {
                Vector3 forward = GetReferenceForwardFlat();
                if (forward.sqrMagnitude < 0.01f)
                    forward = transform.forward;

                Vector3 right = Vector3.Cross(Vector3.up, forward).normalized;
                float side = Mathf.Sign(Vector3.Dot(entry.componentRoot.position - referencePos, right));
                if (Mathf.Abs(side) < 0.01f)
                    side = 1f;

                targetPos = referencePos
                    + forward * hiddenItemsForwardDistance
                    + right * (side * hiddenItemsForwardSpread)
                    + Vector3.up * moveAwayUpOffset;
            }
            else
            {
                Vector3 dir = (entry.componentRoot.position - referencePos).normalized;
                if (dir.sqrMagnitude < 0.01f)
                    dir = (entry.componentRoot.position - transform.position).normalized;
                if (dir.sqrMagnitude < 0.01f)
                    dir = Vector3.forward;

                targetPos = entry.componentRoot.position + dir * moveAwayDistance + Vector3.up * moveAwayUpOffset;
            }

            Vector3 targetScale = Vector3.one * hiddenScaleMultiplier;
            StartCoroutine(AnimateAndHide(entry.componentRoot, duration, targetPos, targetScale));
        }

        if (entry.libraryWindowRoot != null && entry.libraryWindowRoot.gameObject.activeInHierarchy)
            StartCoroutine(AnimateAndHide(entry.libraryWindowRoot, duration));
    }

    private void RestoreEntryFromHidden(LibraryComponentEntry entry, float duration)
    {
        if (entry.componentRoot != null)
        {
            entry.componentRoot.gameObject.SetActive(true);
            Transform anchor = GetAnchor(entry);
            if (anchor != null)
            {
                Vector3 returnScale = GetOriginalScale(entry.componentRoot);
                StartCoroutine(AnimateTransform(entry.componentRoot, anchor.position, anchor.rotation, returnScale, duration));
            }
        }

        if (entry.libraryWindowRoot != null)
        {
            entry.libraryWindowRoot.gameObject.SetActive(true);
            entry.libraryWindowRoot.localScale = Vector3.zero;
            if (originalWindowScale.TryGetValue(entry.libraryWindowRoot, out Vector3 winScale))
                StartCoroutine(AnimateScale(entry.libraryWindowRoot, winScale, duration * 0.8f));
        }
    }

    private IEnumerator AnimateAndHide(Transform target, float duration)
    {
        if (target == null)
            yield break;

        yield return StartCoroutine(AnimateScale(target, Vector3.zero, duration));
        target.gameObject.SetActive(false);
    }

    private IEnumerator AnimateAndHide(Transform target, float duration, Vector3 targetPos, Vector3 targetScale)
    {
        if (target == null)
            yield break;

        yield return StartCoroutine(AnimateTransform(target, targetPos, target.rotation, targetScale, duration));
        target.gameObject.SetActive(false);
    }

    private IEnumerator AnimateTransform(Transform target, Vector3 targetPos, Quaternion targetRot, Vector3 targetScale, float duration)
    {
        if (target == null)
            yield break;

        Vector3 startPos = target.position;
        Quaternion startRot = target.rotation;
        Vector3 startScale = target.localScale;

        if (duration <= 0f)
        {
            target.position = targetPos;
            target.rotation = targetRot;
            target.localScale = targetScale;
            yield break;
        }

        float elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = Mathf.Clamp01(elapsed / duration);
            float eased = movementCurve != null ? movementCurve.Evaluate(t) : t;

            target.position = Vector3.Lerp(startPos, targetPos, eased);
            target.rotation = Quaternion.Slerp(startRot, targetRot, eased);
            target.localScale = Vector3.Lerp(startScale, targetScale, eased);

            yield return null;
        }

        target.position = targetPos;
        target.rotation = targetRot;
        target.localScale = targetScale;
    }

    private IEnumerator AnimateScale(Transform target, Vector3 targetScale, float duration)
    {
        if (target == null)
            yield break;

        Vector3 startScale = target.localScale;
        if (duration <= 0f)
        {
            target.localScale = targetScale;
            yield break;
        }

        float elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = Mathf.Clamp01(elapsed / duration);
            float eased = movementCurve != null ? movementCurve.Evaluate(t) : t;
            target.localScale = Vector3.Lerp(startScale, targetScale, eased);
            yield return null;
        }

        target.localScale = targetScale;
    }

    private void PrepareInitialState()
    {
        currentState = ScenarioState.Idle;
        selectedEntry = null;

        SetBackButtonVisible(false);
        SetStartButtonEnabled(true);

        RestoreCaseDoorState();

        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry == null || entry.componentRoot == null)
                continue;

            bool showInIntro = introComponents.Contains(entry);

            entry.componentRoot.gameObject.SetActive(showInIntro);
            SetComponentPhysicsAnimated(entry.componentRoot, showInIntro);

            if (entry.libraryWindowRoot != null)
                entry.libraryWindowRoot.gameObject.SetActive(false);

            if (showInIntro)
                entry.componentRoot.localScale = GetOriginalScale(entry.componentRoot);
        }
    }

    private void CollectUniqueEntries()
    {
        allComponents.Clear();

        AddUniqueEntries(introComponents);
        AddUniqueEntries(additionalComponents);
    }

    private void EnsureAutoGeneratedSceneData()
    {
        if (autoGenerateWindows)
            GenerateWindowsIfMissing();

        if (autoGenerateArcLayout)
            GenerateArcLayout();

        if (autoGenerateRevealAnchors)
            GenerateRevealAnchorsIfMissing();
    }

    private void GenerateWindowsIfMissing()
    {
        Transform parent = windowParent != null ? windowParent : transform;

        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry == null)
                continue;

            if (entry.libraryWindowRoot == null)
            {
                GameObject created;
                if (windowPrefab != null)
                    created = Instantiate(windowPrefab, parent);
                else
                    created = CreatePlaceholderWindow(i, entry.id, parent);

                created.name = string.IsNullOrWhiteSpace(entry.id)
                    ? "LibraryWindow_" + i
                    : "LibraryWindow_" + entry.id;
                entry.libraryWindowRoot = created.transform;
            }

            var windowBridge = entry.libraryWindowRoot.GetComponent<LearningScenarioComponentWindow>();
            if (windowBridge == null)
                windowBridge = entry.libraryWindowRoot.gameObject.AddComponent<LearningScenarioComponentWindow>();

            windowBridge.scenario = this;
            windowBridge.componentId = entry.id;
            windowBridge.componentRoot = entry.componentRoot;

            if (entry.libraryAnchor == null)
                entry.libraryAnchor = entry.libraryWindowRoot;
        }
    }

    private GameObject CreatePlaceholderWindow(int index, string id, Transform parent)
    {
        GameObject root = new GameObject(string.IsNullOrWhiteSpace(id)
            ? "AutoWindow_" + index
            : "AutoWindow_" + id);
        root.transform.SetParent(parent, false);

        float width = Mathf.Max(0.05f, placeholderWindowSize.x);
        float height = Mathf.Max(0.05f, placeholderWindowSize.y);
        float depth = Mathf.Max(0.005f, placeholderWindowDepth);

        GameObject panel = GameObject.CreatePrimitive(PrimitiveType.Cube);
        panel.name = "Panel";
        panel.transform.SetParent(root.transform, false);
        panel.transform.localPosition = new Vector3(0f, -0.005f, 0f);
        panel.transform.localRotation = Quaternion.identity;
        panel.transform.localScale = new Vector3(width, height, depth);

        var panelRenderer = panel.GetComponent<Renderer>();
        if (panelRenderer != null)
        {
            Material panelMat = new Material(Shader.Find("Standard"));
            panelMat.color = placeholderWindowColor;
            panelRenderer.material = panelMat;
        }

        GameObject border = GameObject.CreatePrimitive(PrimitiveType.Cube);
        border.name = "Border";
        border.transform.SetParent(root.transform, false);
        border.transform.localPosition = Vector3.zero;
        border.transform.localRotation = Quaternion.identity;
        border.transform.localScale = new Vector3(width + 0.01f, height + 0.01f, depth * 0.4f);

        var borderRenderer = border.GetComponent<Renderer>();
        if (borderRenderer != null)
        {
            Material borderMat = new Material(Shader.Find("Standard"));
            borderMat.color = placeholderBorderColor;
            borderRenderer.material = borderMat;
        }

        GameObject header = GameObject.CreatePrimitive(PrimitiveType.Cube);
        header.name = "Header";
        header.transform.SetParent(root.transform, false);
        header.transform.localPosition = new Vector3(0f, (height * 0.5f) - 0.03f, -(depth * 0.28f));
        header.transform.localRotation = Quaternion.identity;
        header.transform.localScale = new Vector3(width * 0.92f, 0.045f, depth * 0.45f);

        var headerRenderer = header.GetComponent<Renderer>();
        if (headerRenderer != null)
        {
            Material headerMat = new Material(Shader.Find("Standard"));
            headerMat.color = placeholderHeaderColor;
            headerRenderer.material = headerMat;
        }

        GameObject glow = GameObject.CreatePrimitive(PrimitiveType.Cube);
        glow.name = "Glow";
        glow.transform.SetParent(root.transform, false);
        glow.transform.localPosition = new Vector3(0f, -height * 0.2f, depth * 0.1f);
        glow.transform.localRotation = Quaternion.identity;
        glow.transform.localScale = new Vector3(width * 0.65f, 0.03f, depth * 0.25f);

        var glowRenderer = glow.GetComponent<Renderer>();
        if (glowRenderer != null)
        {
            Material glowMat = new Material(Shader.Find("Standard"));
            glowMat.color = new Color(0.95f, 0.95f, 0.98f, 1f);
            glowRenderer.material = glowMat;
        }

        BoxCollider collider = root.AddComponent<BoxCollider>();
        collider.size = new Vector3(width, height, depth * 2f);
        collider.center = Vector3.zero;

        var placeholderLabel = root.AddComponent<LearningScenarioWindowLabel>();
        placeholderLabel.labelText = string.IsNullOrWhiteSpace(id) ? "Component" : id;
        placeholderLabel.subtitleText = "Inspect";
        placeholderLabel.textHeight = 0.01f;

        return root;
    }

    private void GenerateArcLayout()
    {
        if (allComponents.Count == 0)
            return;

        Vector3 referencePos = GetLibraryCenterPosition();
        Vector3 flatForward = GetReferenceForwardFlat();
        if (flatForward.sqrMagnitude < 0.01f)
            flatForward = transform.forward;

        int count = allComponents.Count;
        for (int i = 0; i < count; i++)
        {
            var entry = allComponents[i];
            if (entry == null)
                continue;

            Transform target = entry.libraryAnchor != null ? entry.libraryAnchor : entry.libraryWindowRoot;
            if (target == null)
                continue;

            float t = count == 1 ? 0.5f : (float)i / (count - 1);
            float yaw = Mathf.Lerp(-libraryArcDegrees * 0.5f, libraryArcDegrees * 0.5f, t);
            Vector3 dir = Quaternion.AngleAxis(yaw, Vector3.up) * flatForward;
            Vector3 pos = referencePos + dir * libraryRadius;
            pos.y = Mathf.Max(referencePos.y + libraryHeightOffset, minimumLibraryY);

            target.position = pos;
            target.rotation = Quaternion.LookRotation(referencePos - pos, Vector3.up);
        }
    }

    private void GenerateRevealAnchorsIfMissing()
    {
        int needed = introComponents.Count;
        if (needed <= 0)
            return;

        if (introRevealAnchors == null)
            introRevealAnchors = new List<Transform>();

        while (introRevealAnchors.Count < needed)
            introRevealAnchors.Add(null);

        Vector3 center;
        if (pcCaseDoorObject != null)
            center = pcCaseDoorObject.position;
        else if (pcCaseDoor != null)
            center = pcCaseDoor.transform.position;
        else
            center = transform.position;

        Vector3 flatForward = GetReferenceForwardFlat();
        if (flatForward.sqrMagnitude < 0.01f)
            flatForward = transform.forward;

        for (int i = 0; i < needed; i++)
        {
            if (introRevealAnchors[i] != null)
                continue;

            GameObject go = new GameObject("AutoRevealAnchor_" + i);
            go.transform.SetParent(transform, true);

            float t = needed == 1 ? 0.5f : (float)i / (needed - 1);
            float yaw = Mathf.Lerp(-revealArcDegrees * 0.5f, revealArcDegrees * 0.5f, t);
            Vector3 dir = Quaternion.AngleAxis(yaw, Vector3.up) * flatForward;

            go.transform.position = center + dir * revealDistanceFromCase + Vector3.up * revealHeightFromCase;
            go.transform.rotation = Quaternion.LookRotation(flatForward, Vector3.up);

            introRevealAnchors[i] = go.transform;
        }
    }

    private void AddUniqueEntries(List<LibraryComponentEntry> source)
    {
        if (source == null)
            return;

        for (int i = 0; i < source.Count; i++)
        {
            var entry = source[i];
            if (entry == null || entry.componentRoot == null)
                continue;

            bool exists = false;
            for (int j = 0; j < allComponents.Count; j++)
            {
                if (allComponents[j] != null && allComponents[j].componentRoot == entry.componentRoot)
                {
                    exists = true;
                    break;
                }
            }

            if (!exists)
                allComponents.Add(entry);
        }
    }

    private void CacheOriginalData()
    {
        originalComponentData.Clear();
        originalWindowScale.Clear();

        if (pcCaseDoorObject != null)
        {
            hasDoorPose = true;
            doorPose = new DoorPoseData
            {
                position = pcCaseDoorObject.position,
                rotation = pcCaseDoorObject.rotation,
                active = pcCaseDoorObject.gameObject.activeSelf
            };
        }
        else
        {
            hasDoorPose = false;
        }

        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry == null)
                continue;

            if (entry.componentRoot != null && !originalComponentData.ContainsKey(entry.componentRoot))
            {
                originalComponentData.Add(entry.componentRoot, new CachedTransformData
                {
                    position = entry.componentRoot.position,
                    rotation = entry.componentRoot.rotation,
                    localScale = entry.componentRoot.localScale
                });
            }

            if (entry.libraryWindowRoot != null && !originalWindowScale.ContainsKey(entry.libraryWindowRoot))
                originalWindowScale.Add(entry.libraryWindowRoot, entry.libraryWindowRoot.localScale);
        }
    }

    private Transform GetAnchor(LibraryComponentEntry entry)
    {
        if (entry == null)
            return null;

        if (entry.libraryAnchor != null)
            return entry.libraryAnchor;

        if (entry.libraryWindowRoot != null)
            return entry.libraryWindowRoot;

        return null;
    }

    private Vector3 GetReferencePosition()
    {
        if (playerHead != null)
            return playerHead.position;

        if (Camera.main != null)
            return Camera.main.transform.position;

        return transform.position;
    }

    private Vector3 GetLibraryCenterPosition()
    {
        if (libraryCenterOverride != null)
            return libraryCenterOverride.position;

        Vector3 reference = GetReferencePosition();
        Vector3 flatForward = GetReferenceForwardFlat();
        if (flatForward.sqrMagnitude < 0.01f)
            flatForward = transform.forward;

        return reference + flatForward * libraryForwardOffset;
    }

    private Vector3 GetReferenceForwardFlat()
    {
        Vector3 forward;

        if (playerHead != null)
            forward = playerHead.forward;
        else if (Camera.main != null)
            forward = Camera.main.transform.forward;
        else
            forward = transform.forward;

        forward.y = 0f;
        return forward.normalized;
    }

    private Vector3 GetOriginalScale(Transform target)
    {
        if (target != null && originalComponentData.TryGetValue(target, out CachedTransformData cached))
            return cached.localScale;

        return Vector3.one;
    }

    private void SetStartButtonEnabled(bool enabled)
    {
        if (startButton != null)
            startButton.interactable = enabled;
    }

    private void SetBackButtonVisible(bool visible)
    {
        if (backButton == null)
            return;

        backButton.gameObject.SetActive(visible);
        backButton.interactable = visible;
    }

    private void SetLibraryInteractable(bool enabled)
    {
        for (int i = 0; i < allComponents.Count; i++)
        {
            var entry = allComponents[i];
            if (entry == null || entry.libraryWindowRoot == null)
                continue;

            var colliders = entry.libraryWindowRoot.GetComponentsInChildren<Collider>(true);
            for (int c = 0; c < colliders.Length; c++)
                colliders[c].enabled = enabled;

            var buttons = entry.libraryWindowRoot.GetComponentsInChildren<Button>(true);
            for (int b = 0; b < buttons.Length; b++)
                buttons[b].interactable = enabled;
        }
    }

    private void SetInspectRotationEnabled(Transform componentRoot, bool enabled)
    {
        if (componentRoot == null)
            return;

        var rotate = componentRoot.GetComponent<VRInspectRotate>();
        if (rotate == null)
            rotate = componentRoot.gameObject.AddComponent<VRInspectRotate>();

        rotate.referenceFrame = playerHead != null ? playerHead : (Camera.main != null ? Camera.main.transform : null);
        rotate.SetInspectEnabled(enabled);
    }

    private void SetComponentPhysicsAnimated(Transform componentRoot, bool asAnimated)
    {
        if (componentRoot == null)
            return;

        var bodies = componentRoot.GetComponentsInChildren<Rigidbody>(true);
        for (int i = 0; i < bodies.Length; i++)
        {
            bodies[i].isKinematic = asAnimated;
            bodies[i].useGravity = !asAnimated;
            if (asAnimated)
            {
                bodies[i].linearVelocity = Vector3.zero;
                bodies[i].angularVelocity = Vector3.zero;
            }
        }
    }

    private void SetMovementLocked(bool locked)
    {
        if (locked)
        {
            runtimeDisabledMovementBehaviours.Clear();

            for (int i = 0; i < movementBehavioursToDisable.Count; i++)
            {
                Behaviour behaviour = movementBehavioursToDisable[i];
                if (behaviour == null || !behaviour.enabled)
                    continue;

                behaviour.enabled = false;
                runtimeDisabledMovementBehaviours.Add(behaviour);
            }

            HandLocomotionJoystick[] joystickLocomotion = FindObjectsByType<HandLocomotionJoystick>(FindObjectsSortMode.None);
            for (int i = 0; i < joystickLocomotion.Length; i++)
            {
                if (joystickLocomotion[i] == null || !joystickLocomotion[i].enabled)
                    continue;

                joystickLocomotion[i].enabled = false;
                runtimeDisabledMovementBehaviours.Add(joystickLocomotion[i]);
            }

            return;
        }

        for (int i = 0; i < runtimeDisabledMovementBehaviours.Count; i++)
        {
            Behaviour behaviour = runtimeDisabledMovementBehaviours[i];
            if (behaviour != null)
                behaviour.enabled = true;
        }

        runtimeDisabledMovementBehaviours.Clear();
    }

    private IEnumerator AnimateCaseDoorFlyAway()
    {
        if (pcCaseDoorObject == null)
            yield break;

        pcCaseDoorObject.gameObject.SetActive(true);
        SetComponentPhysicsAnimated(pcCaseDoorObject, true);

        Vector3 reference = GetReferencePosition();
        Vector3 dir = (pcCaseDoorObject.position - reference).normalized;
        if (dir.sqrMagnitude < 0.01f)
            dir = transform.right;

        Vector3 targetPos = pcCaseDoorObject.position + dir * caseDoorFlyDistance + Vector3.up * caseDoorFlyUpOffset;
        Quaternion targetRot = pcCaseDoorObject.rotation * Quaternion.Euler(0f, caseDoorFlyRotateDegrees, 0f);

        yield return StartCoroutine(AnimateTransform(
            pcCaseDoorObject,
            targetPos,
            targetRot,
            pcCaseDoorObject.localScale,
            caseDoorFlyDuration));

        if (hideCaseDoorAfterFly)
            pcCaseDoorObject.gameObject.SetActive(false);
    }

    private void RestoreCaseDoorState()
    {
        if (!hasDoorPose || pcCaseDoorObject == null)
            return;

        pcCaseDoorObject.gameObject.SetActive(doorPose.active);
        pcCaseDoorObject.position = doorPose.position;
        pcCaseDoorObject.rotation = doorPose.rotation;
    }

    private void OnValidate()
    {
        if (hiddenScaleMultiplier < 0.01f)
            hiddenScaleMultiplier = 0.01f;

        if (inspectScaleMultiplier < 0.1f)
            inspectScaleMultiplier = 0.1f;

        if (moveDuration < 0f)
            moveDuration = 0f;

        if (caseDoorFlyDuration < 0f)
            caseDoorFlyDuration = 0f;

        if (libraryRadius < 0.2f)
            libraryRadius = 0.2f;

        if (libraryArcDegrees < 1f)
            libraryArcDegrees = 1f;

        if (revealDistanceFromCase < 0.05f)
            revealDistanceFromCase = 0.05f;

        if (placeholderWindowDepth < 0.005f)
            placeholderWindowDepth = 0.005f;

        placeholderWindowSize.x = Mathf.Max(0.05f, placeholderWindowSize.x);
        placeholderWindowSize.y = Mathf.Max(0.05f, placeholderWindowSize.y);

        if (libraryForwardOffset < 0.1f)
            libraryForwardOffset = 0.1f;

        if (hiddenItemsForwardDistance < 0.1f)
            hiddenItemsForwardDistance = 0.1f;
    }
}
